-- MySQL Script generated by MySQL Workbench
-- Sat Sep 27 10:50:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema midterm_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema midterm_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `midterm_db` DEFAULT CHARACTER SET utf8 ;
USE `midterm_db` ;

-- -----------------------------------------------------
-- Table `midterm_db`.`customers_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `midterm_db`.`customers_table` (
  `cust_id` INT NOT NULL AUTO_INCREMENT,
  `cust_name` VARCHAR(45) NOT NULL,
  `cust_address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cust_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
